import numpy as np 
import scipy as sp 

print("NUMPY VERSION : ", np.__version__) 
print("SCIPY VERSION : ", sp.__version__) 

# FOR MATRIX AND SUCH RELATED OPERATIONS WE USE THE LIBRARIES SUCH AS SCIPY AND NUMPY !! 
# TO HANDLE MULTIDIMENSIONAL ARRAYS AND CARRY OUT OPERATIONS ON THEM AS EFFICIENTLY AS POSSIBLE WE CAN 
# MAKE USE OF THESE PACKAGES. 
# COMPLEX DATATYPES CAN ALSO BE USED ALONG WITH THESE LIBRARIES !!

# SCIPY IS BUILD ON TOP OF THE NUMPY PACKAGE AND PROVIDES MANY OF THE MATHEMATICAL FUNCTIONS ALREADY. 
# LIKE - LINEAR ALGEBRA, NUMERICAL CALCULUS AND STATISTICS ETC. 
# SCIPY MAKES USE OF C AND FORTRAN BEHIND THE SCENES. THUS COMBINING BEST OF BOTH THE WORLDS. 

# SOME COMMON OPERATIONS WITH THE NUMPY PACKAGE !! 
arr = np.array([1,2,3,4,5,6,8,9,10,11,12]) 
print(arr)

arr.shape = 3, 4
print(arr)
