from collections import deque 

# IF YOU HAVE A LOT OF front AND back ACCESSES PRESENT IN THE FILE. THEN MAKE USE OF deque. 
# IF YOU HAVE A LOT OF existence CHECKS PRESENT IN THE CODE THEN MAKE USE OF set DATA STRUCTURE. 
